[package]
name = "nolik-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.17"
crossterm = "0.22"
unicode-width = "0.1.5"

codec = { package = "parity-scale-codec", features = ["derive"], version = "2.0.0" }
sp-core = { version = "5.0.0", git = "https://github.com/paritytech/substrate.git", branch = "master" }
sp-keyring = { version = "5.0.0", git = "https://github.com/paritytech/substrate.git", branch = "master" }

sodiumoxide = "0.2.7"
clipboard = "0.5.0"
#zeroize = "1.5.2"
#rand_core = { version = "0.6", features = ["getrandom"] }
#crypto_box = "0.7.1"
#ed25519-compact = "0.1"
#hex = "0.4"
#base64 = "0.13.0"
bs58 = "0.4.0"
